- name: Add users to groups
  ldap_attrs:
 #   server_uri: "{{ldap_server_uri}}"
    bind_dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    bind_pw: "{{ openldap_admin_password }}"
    dn: "cn={{ group_name_add }}, ou=Groups, {{ openldap_user_base }}"
    attributes:  
      userPassword: "{{ passwordHash }}"
      memberuid: "{{ uid }}"
    state: present
  tags: delete_user_from_group 
