- name: Prepare slapd installation answers
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - question: slapd/backend
      value: MDB
      vtype: string
    - question: slapd/move_old_database
      value: 'true'
      vtype: boolean
    - question: slapd/dump_database_destdir
      value: /var/backups/slapd-VERSION
      vtype: string
    - question: slapd/allow_ldap_v2
      value: 'false'
      vtype: boolean
    - question: slapd/purge_database
      value: 'false'
      vtype: boolean
    - question: slapd/domain
      value: "{{ domain_name }}"
      vtype: string
    - question: shared/organization
      value: "{{ openldap_org }}"
      vtype: string
    - question: slapd/password1
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/password2
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/internal/generated_adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/internal/adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
  tags: install_server

- name: Installing packages
  apt:
    name:
      - slapd
      - ldap-utils
      # These are needed to be able to install python-ldap
      - build-essential
      - python3-dev
      - python3-pip
      - libldap2-dev
      - libsasl2-dev
      - lcov
      - valgrind
      - debconf-utils
    state: present
  tags: install_server

- name: Make sure setuptools and wheel pip modules are present (needed to build python-ldap)
  pip:
    name:
      - setuptools
      - wheel
    state: present
  tags: install_server

- name: Make sure python-ldap pip module is present
  pip:
    name:
      - python-ldap
    state: present
  tags: install_server

- name: Check to see if we have loaded password module for openldap
  command: ldapsearch -H ldapi:// -Y EXTERNAL -b "cn=module{0},cn=config" -LLL -Q olcModuleLoad={1}pw-sha2
  register: pw_sha2
  changed_when: pw_sha2.stdout == ""
  tags: install_server

- name: Copy ldif for pw module if needed
  copy:
    src: pw.ldif
    dest: /tmp/pw.ldif
  when: pw_sha2.stdout == ""
  tags: install_server

- name: Load password module for openldap if we haven't yet
  command: ldapmodify -Q -Y EXTERNAL -H ldapi:// -f /tmp/pw.ldif
  when: pw_sha2.stdout == ""
  tags: install_server

- name: Copy ldif for pw module if needed
  copy:
    src: openssh-lpk.ldif
    dest: /tmp/openssh-lpk.ldif
  tags: install_server

- name: Load password module for openldap if we haven't yet
  command: ldapadd -H ldapi:/// -Y EXTERNAL -f /tmp/openssh-lpk.ldif 
  tags: install_server

- name: Copy ldif for logs module if needed
  copy:
    src: log.ldif
    dest: /tmp/log.ldif
  tags: install_server

- name: Load password module for openldap if we haven't yet
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/log.ldif
  tags: install_server


- name: Change Rsyslog for logging
  shell: | 
          cat >> /etc/rsyslog.conf << "EOF" 
          LOCAL4.* /var/log/slapd.log
          EOF
  tags: install_server

- name: restart Rsyslog
  command: systemctl restart rsyslog
  tags: install_server

- name: Set a password for the admin user
  community.general.ldap_passwd:
    dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    passwd: "{{ openldap_admin_password }}"
  tags: install_server