- name: install openldap client
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive
  with_items:
    - nslcd
    - ldap-utils
  tags: install_client  

- name: copy nsswitch and nslcd config
  template:
    src: "client/{{item}}.j2"
    dest: /etc/{{item}}
  with_items:
    - nsswitch.conf
    - nslcd.conf
    - nscd.conf
  tags: install_client  

- name: copy pam common-session config
  template:
    src: "client/{{item}}.j2"
    dest: /etc/pam.d/{{item}}
  with_items:
    - common-session
  tags: install_client  

- name: restart nslcd service
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - nscd
    - nslcd
  tags: install_client  
