- name: Install openldap
  include_tasks: install_ldap_server.yml
  tags: install_server

- name: create user
  include_tasks: create_user.yml
  tags: create

- name: delete user
  include_tasks: delete_user.yml
  tags: delete

- name: search users
  include_tasks: search_users.yml
  tags: search  
