---
- name: Prepare slapd installation answers
  debconf:
    name: slapd
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - question: slapd/backend
      value: HDB
      vtype: string
    - question: slapd/move_old_database
      value: 'true'
      vtype: boolean
    - question: slapd/dump_database_destdir
      value: /var/backups/slapd-VERSION
      vtype: string
    - question: slapd/allow_ldap_v2
      value: 'false'
      vtype: boolean
    - question: slapd/purge_database
      value: 'false'
      vtype: boolean
    - question: slapd/domain
      value: "{{ domain_name }}"
      vtype: string
    - question: shared/organization
      value: "{{ openldap_org }}"
      vtype: string
    - question: slapd/password1
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/password2
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/internal/generated_adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
    - question: slapd/internal/adminpw
      value: "{{ openldap_admin_password }}"
      vtype: password
  tags: install

- name: Installing packages
  apt:
    name:
      - slapd
      - ldap-utils
      # These are needed to be able to install python-ldap
      - build-essential
      - python3-dev
      - python3-pip
      - libldap2-dev
      - libsasl2-dev
      - lcov
      - valgrind
    state: present
  tags: install

- name: Make sure setuptools and wheel pip modules are present (needed to build python-ldap)
  pip:
    name:
      - setuptools
      - wheel
    state: present
  tags: install

- name: Make sure python-ldap pip module is present
  pip:
    name:
      - python-ldap
    state: present
  tags: install

- name: Check to see if we have loaded password module for openldap
  command: ldapsearch -H ldapi:// -Y EXTERNAL -b "cn=module{0},cn=config" -LLL -Q olcModuleLoad={1}pw-sha2
  register: pw_sha2
  changed_when: pw_sha2.stdout == ""
  tags: install

- name: Copy ldif for pw module if needed
  copy:
    src: pw.ldif
    dest: /tmp/pw.ldif
  when: pw_sha2.stdout == ""
  tags: install

- name: Load password module for openldap if we haven't yet
  command: ldapmodify -Q -Y EXTERNAL -H ldapi:// -f /tmp/pw.ldif
  when: pw_sha2.stdout == ""
  tags: install

- name: Set a password for the admin user
  community.general.ldap_passwd:
    dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    passwd: "{{ openldap_admin_password }}"
  tags: install

- name: Make sure we have a parent entry for users
  community.general.ldap_entry:
    dn: "ou={{ item }},dc={{ openldap_org }},dc={{ openldap_tld }}"
    objectClass: organizationalUnit
    bind_dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    bind_pw: "{{ openldap_admin_password }}"
  with_items: "{{ openldap_ous }}"
  tags: delete, create

- name: Delete users to regenerate
  ldap_entry:
    dn: "uid={{ firstName|lower }}.{{ lastName|lower }},ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
    objectClass:
      - inetOrgPerson
    state: absent
    bind_dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    bind_pw: "{{ openldap_admin_password }}"
  tags: delete

- name: Create users
  ldap_entry:
    dn: "uid={{ firstName|lower }}.{{ lastName|lower }},ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
    objectClass:
      - inetOrgPerson
    state: present
    bind_dn: "cn=admin,dc={{ openldap_org }},dc={{ openldap_tld }}"
    bind_pw: "{{ openldap_admin_password }}"
    attributes:
      userPassword: "{{ passwordHash }}"
      sn: "{{ lastName }}"
      givenName: "{{ firstName }}"
      cn: "{{ firstName }} {{ lastName }}"
      displayName: "{{ firstName }} {{ lastName }}"
  tags: create

- name: Return all entries within the 'people' organizational unit.
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
  register: ldap_groups
  tags: search

- debug: 
    msg: "{{ ldap_groups }}"
  tags: search

- name: Return GIDs for all people
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
    scope: "children"
    attrs:
      - "gidNumber"
    schema: true
  register: ldap_group_gids
  tags: search

- debug: 
    msg: "{{ ldap_group_gids }}"
  tags: search