- name: Return all entries within the 'people' organizational unit.
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
  register: ldap_groups
  tags: search

- name: Return INFO for all people
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
    scope: "subordinate"
    attrs:
      - "gidNumber"
      - "uidNumber"
      - "uid"
  register: ldap_group_gids
  tags: search
  
- debug: 
    msg: "{{ ldap_group_gids }}"
  tags: search

- name: Return INFO for all GROUPS
  community.general.ldap_search:
    dn: "ou=Groups,dc={{ openldap_org }},dc={{ openldap_tld }}"
    scope: "subordinate"
    attrs:
      - "gidNumber"
      - "cn"
  register: ldap_group_gids
  tags: search
  
- debug: 
    msg: "{{ ldap_group_gids }}"
  tags: search