- name: Return all entries within the 'people' organizational unit.
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
  register: ldap_groups
  tags: search

- debug: 
    msg: "{{ ldap_groups }}"
  tags: search

- name: Return GIDs for all people
  community.general.ldap_search:
    dn: "ou=People,dc={{ openldap_org }},dc={{ openldap_tld }}"
    scope: "subordinate"
    attrs:
      - "gidNumber"
      - "uidNumber"
  #  schema: true
  register: ldap_group_gids
  tags: search
  
- debug: 
    msg: "{{ ldap_group_gids }}"
  tags: search